version: '3.9'
services:
  mysql:
    container_name: cossim_mysql
    image: mysql:5.7
    volumes:
      - ./data/var/lib/mysql:/var/lib/mysql
    command: [
      '--character-set-server=utf8mb4',
    ]
    expose:
      - "3306"
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Hitosea@123.."
      MYSQL_DATABASE: coss
      MYSQL_USER: coss
      MYSQL_PASSWORD: "Hitosea@123.."
      MYSQL_TCP_PORT: '3306'
      MYSQL_ROOT_HOST: '%'
    #      MARIADB_AUTO_UPGRADE: 'true'
    #      MARIADB_DISABLE_UPGRADE_BACKUP: 'true'
    healthcheck:
      test: mysqladmin ping -h mysql -P 3306 -p$$MYSQL_ROOT_PASSWORD
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
  minio:
    image: hub.hitosea.com/cossim/minio
    container_name: cossim_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: Hitosea@123..
    volumes:
      - ./data/var/lib/minio:/data
    command: server /data --console-address ":9001"
  rabbitmq:
    image: "rabbitmq:management"
    container_name: cossim_rabbitmq
    hostname: rabbitmq3-management-master
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "1"
    volumes:
      - "./data/var/lib/rabbitmq:/var/lib/rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: Hitosea@123..
  redis:
    image: redis:latest
    container_name: cossim_redis
    ports:
      - 6379:6379
    command: redis-server --requirepass Hitosea@123..
  dtm:
    container_name: cossim_dtm
    image: hub.hitosea.com/cossim/dtm
    ports:
      - '36789:36789'
      - '36790:36790'
  consul:
    image: hub.hitosea.com/cossim/consul:latest
    container_name: cossim_consul
    volumes:
      - ./data/var/lib/consul:/consul/data
      - ./config/common/consul.json:/etc/consul/consul-config.json
    command: consul agent -server -bootstrap-expect=1 -client=0.0.0.0 -ui -data-dir=/consul/data -config-dir=/etc/consul
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'
  hipush:
    container_name: cossim_push
    image: hub.hitosea.com/cossim/hipush
    volumes:
      - ./config/common/hipush.yaml:/config/config.yaml
      # 如果启用了ios推送，需要将推送证书挂载到容器中
      #- /Users/macos-15/Desktop/key/AuthKey_UU2D9Z4ANF.p8:/config/key/AuthKey_UU2D9Z4ANF.p8
    command:
      - "-config"
      - "/config/config.yaml"
    ports:
      - "7070:7070"
      - "7071:7071"
    restart: on-failure
  gateway:
    container_name: cossim_gateway
    image: hub.hitosea.com/cossim/gateway
    command:
      - "--discover"
      - "--remote-config"
      - "--config-center-addr"
      - "consul:8500"
    ports:
      - "8080:8080"
    environment:
      CONSUL_HTTP_TOKEN:
    restart: on-failure
  admin_service:
    container_name: cossim_admin
    image: hub.hitosea.com/cossim/admin
    command:
      - "--discover"
      - "--register"
      - "--remote-config"
      - "--config-center-addr"
      - "consul:8500"
    volumes:
      - ./config/pgp:/.cache
    depends_on:
      - dtm
      - redis
      - rabbitmq
      - group_service
      - relation_service
      - user_service
      - msg_service
    environment:
      CONSUL_HTTP_TOKEN:
    restart: on-failure
  live_service:
    container_name: cossim_live
    image: hub.hitosea.com/cossim/live
    command:
      - "--discover"
      - "--register"
      - "--remote-config"
      - "--config-center-addr"
      - "consul:8500"
    volumes:
      - ./config/pgp:/.cache
    depends_on:
      - consul
      - redis
      - user_service
      - relation_service
    environment:
      CONSUL_HTTP_TOKEN:
    restart: on-failure
  msg_service:
    container_name: cossim_msg_service
    image: hub.hitosea.com/cossim/msg
    command:
      - "--discover"
      - "--register"
      - "--remote-config"
      - "--config-center-addr"
      - "consul:8500"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./config/pgp:/.cache
    environment:
      CONSUL_HTTP_TOKEN:
    restart: on-failure
  relation_service:
    container_name: cossim_relation_service
    image: hub.hitosea.com/cossim/relation
    command:
      - "--discover"
      - "--register"
      - "--remote-config"
      - "--config-center-addr"
      - "consul:8500"
    volumes:
      - ./config/pgp:/.cache
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      CONSUL_HTTP_TOKEN:
    restart: on-failure
  user_service:
    container_name: cossim_user_service
    image: hub.hitosea.com/cossim/user
    command:
      - "--discover"
      - "--register"
      - "--remote-config"
      - "--config-center-addr"
      - "consul:8500"
    volumes:
      - ./config/pgp:/.cache
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      CONSUL_HTTP_TOKEN:
    restart: on-failure
  group_service:
    container_name: cossim_group_service
    image: hub.hitosea.com/cossim/group
    command:
      - "--discover"
      - "--register"
      - "--remote-config"
      - "--config-center-addr"
      - "consul:8500"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      CONSUL_HTTP_TOKEN:
    restart: on-failure
    volumes:
      - ./config/pgp:/.cache
  storage_service:
    container_name: cossim_storage_service
    image: hub.hitosea.com/cossim/storage
    command:
      - "--discover"
      - "--register"
      - "--remote-config"
      - "--config-center-addr"
      - "consul:8500"
    volumes:
      - ./config/pgp:/.cache
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      CONSUL_HTTP_TOKEN:
    restart: on-failure
