version: '3.9'
services:
  mysql:
    container_name: cossim_mysql
    image: mysql:5.7
    volumes:
    - ./data/var/lib/mysql:/var/lib/mysql
    command: [
      '--character-set-server=utf8mb4',
    ]
    expose:
    - "3306"
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Hitosea@123.."
      MYSQL_DATABASE: coss
      MYSQL_USER: coss
      MYSQL_PASSWORD: "Hitosea@123.."
      MYSQL_TCP_PORT: '3306'
      MYSQL_ROOT_HOST: '%'
#      MARIADB_AUTO_UPGRADE: 'true'
#      MARIADB_DISABLE_UPGRADE_BACKUP: 'true'
    healthcheck:
      test: mysqladmin ping -h mysql -P 3306 -p$$MYSQL_ROOT_PASSWORD
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
  minio:
    image: quay.io/minio/minio
    container_name: cossim_minio
    ports:
    - "9000:9000"
    - "9001:9001"
    expose:
    - "9000"
    - "9001"
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: CHANGEME123
    volumes:
      - ./data/var/lib/minio:/data
    command: server /data --console-address ":9001"
  gateway:
    container_name: cossim_gateway
    image: hub.hitosea.com/cossim/gateway-interface
    volumes:
    - ./config/interface/gateway.yaml:/config/config.yaml
    command:
    - "--config"
    - "/config/config.yaml"
    ports:
    - "8080:8080"
    environment:
      SOME_VARIABLE: some_value
    restart: on-failure
  msg_bff:
    container_name: cossim_msg_bff
    image: hub.hitosea.com/cossim/msg-interface
    command:
    - "--config"
    - "/config/config.yaml"
    volumes:
      - ./config/interface/msg.yaml:/config/config.yaml
    expose:
    - "8081"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SOME_VARIABLE: some_value
    restart: on-failure
  relation_bff:
    container_name: cossim_relation_bff
    image: hub.hitosea.com/cossim/relation-interface
    command:
    - "--config"
    - "/config/config.yaml"
    volumes:
      - ./config/interface/relation.yaml:/config/config.yaml
    expose:
    - "8082"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SOME_VARIABLE: some_value
    restart: on-failure
  user_bff:
    container_name: cossim_user_bff
    image: hub.hitosea.com/cossim/user-interface
    command:
    - "--config"
    - "/config/config.yaml"
    volumes:
      - ./config/interface/user.yaml:/config/config.yaml
    expose:
    - "8083"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SOME_VARIABLE: some_value
    restart: on-failure
  group_bff:
    container_name: cossim_group_bff
    image: hub.hitosea.com/cossim/group-interface
    command:
      - "--config"
      - "/config/config.yaml"
    volumes:
      - ./config/interface/group.yaml:/config/config.yaml
    expose:
      - "8084"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SOME_VARIABLE: some_value
    restart: on-failure
  storgae_bff:
    container_name: cossim_storgae_bff
    image: hub.hitosea.com/cossim/storage-interface
    command:
      - "--config"
      - "/config/config.yaml"
    volumes:
      - ./config/interface/storage.yaml:/config/config.yaml
    expose:
      - "8084"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SOME_VARIABLE: some_value
    restart: on-failure
  msg_service:
    container_name: cossim_msg_service
    image: hub.hitosea.com/cossim/msg-service
    command:
    - "--config"
    - "/config/config.yaml"
    volumes:
      - ./config/service/msg.yaml:/config/config.yaml
    expose:
    - "10000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SOME_VARIABLE: some_value
    restart: on-failure
  relation_service:
    container_name: cossim_relation_service
    image: hub.hitosea.com/cossim/relation-service
    command:
    - "--config"
    - "/config/config.yaml"
    volumes:
      - ./config/service/relation.yaml:/config/config.yaml
    expose:
    - "10001"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SOME_VARIABLE: some_value
    restart: on-failure
  user_service:
    container_name: cossim_user_service
    image: hub.hitosea.com/cossim/user-service
    command:
      - "--config"
      - "/config/config.yaml"
    volumes:
      - ./config/service/user.yaml:/config/config.yaml
    expose:
      - "10002"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SOME_VARIABLE: some_value
    restart: on-failure
  group_service:
    container_name: cossim_group_service
    image: hub.hitosea.com/cossim/group-service
    command:
      - "--config"
      - "/config/config.yaml"
    volumes:
      - ./config/service/group.yaml:/config/config.yaml
    expose:
      - "10005"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SOME_VARIABLE: some_value
    restart: on-failure