name: Msg Interface Docker Image

on:
  push:
    branches:
      # - 'releases/**'
      # - 'main'
      # - 'master'
      - 'dev'
    paths:
      - 'pkg/config/**.go'
      - 'docs/msg*.*'
      - 'interface/msg/**'
jobs:
  build_msg_interface:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 8
        
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20'
      
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Container Registry
      uses: docker/login-action@v2
      with:
        registry: https://${{ secrets.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Build And Push Docker Image
      shell: bash
      run: |
          set -o xtrace
          branch="${GITHUB_REF#refs/heads/}"
          timestamp=`TZ="Asia/Shanghai" date +"%Y%m%d%H%M%S"`
          export VERSION="$branch-$timestamp-solo"
          export GO111MODULE=on
          export GOOS=linux
          export ARCH=all
          export REGISTRY=${{ secrets.REGISTRY }}/cossim
          make docker-build docker-push ACTION=interface NAME=msg TAG=dev REGISTRY=${{ secrets.REGISTRY }}/cossim
